import { Button } from "@/components/ui/button"
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { Separator } from "@/components/ui/separator"
import { DashboardHeader } from "@/components/dashboard-header"
import { ArrowLeft, Download, Printer } from "lucide-react"
import Link from "next/link"

export default function PaymentReceiptPage({ params }: { params: { id: string } }) {
  // In a real app, you would fetch the receipt data based on the ID
  const receiptData = {
    id: params.id,
    date: "March 1, 2025",
    amount: 1450,
    status: "completed",
    method: "Credit Card (•••• 4242)",
    reference: "March 2025 Rent",
    property: "123 Main Street, Apt 4B, San Francisco, CA 94103",
    landlord: "Skyline Properties LLC",
    tenant: "John Doe",
    transactionId: params.id,
    paymentDate: "March 1, 2025 09:15 AM",
  }

  return (
    <div className="flex min-h-screen flex-col">
      <DashboardHeader />
      <div className="flex-1 p-4 md:p-8 pt-6">
        <div className="flex items-center space-x-2 mb-4">
          <Link href="/dashboard/payments/history">
            <Button variant="ghost" size="sm">
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back to Payment History
            </Button>
          </Link>
        </div>

        <div className="max-w-2xl mx-auto">
          <Card className="border-2" id="receipt">
            <CardHeader className="text-center border-b">
              <div className="flex items-center justify-center gap-2 font-bold text-xl mb-2">
                <span className="text-primary">Lease</span>Vault
              </div>
              <CardTitle className="text-2xl">Payment Receipt</CardTitle>
            </CardHeader>
            <CardContent className="p-6 space-y-6">
              <div className="flex justify-between">
                <div>
                  <h3 className="font-medium">Receipt #: {receiptData.id}</h3>
                  <p className="text-sm text-muted-foreground">Date: {receiptData.date}</p>
                </div>
                <div className="text-right">
                  <h3 className="font-medium">Amount Paid</h3>
                  <p className="text-xl font-bold">${receiptData.amount.toFixed(2)}</p>
                </div>
              </div>

              <Separator />

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <h3 className="font-medium mb-1">From</h3>
                  <p className="text-sm">{receiptData.tenant}</p>
                </div>
                <div>
                  <h3 className="font-medium mb-1">To</h3>
                  <p className="text-sm">{receiptData.landlord}</p>
                </div>
              </div>

              <div>
                <h3 className="font-medium mb-1">Property</h3>
                <p className="text-sm">{receiptData.property}</p>
              </div>

              <Separator />

              <div className="space-y-2">
                <h3 className="font-medium">Payment Details</h3>
                <div className="grid grid-cols-2 gap-2 text-sm">
                  <div>Payment Method:</div>
                  <div className="text-right">{receiptData.method}</div>
                  <div>Reference:</div>
                  <div className="text-right">{receiptData.reference}</div>
                  <div>Transaction ID:</div>
                  <div className="text-right">{receiptData.transactionId}</div>
                  <div>Payment Date:</div>
                  <div className="text-right">{receiptData.paymentDate}</div>
                  <div>Status:</div>
                  <div className="text-right font-medium text-green-600">Paid</div>
                </div>
              </div>

              <div className="border-t pt-4 text-center text-sm text-muted-foreground">
                <p>This receipt was automatically generated by LeaseVault.</p>
                <p>Thank you for your payment.</p>
              </div>
            </CardContent>
            <CardFooter className="flex justify-center gap-4 border-t">
              <Button variant="outline" size="sm">
                <Printer className="mr-2 h-4 w-4" />
                Print Receipt
              </Button>
              <Button variant="outline" size="sm">
                <Download className="mr-2 h-4 w-4" />
                Download PDF
              </Button>
            </CardFooter>
          </Card>
        </div>
      </div>
    </div>
  )
}

